import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.ASYNC_CODER_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
const legacyNeedles = ["mi" + "mo", "xi" + "ao" + "mi"]
const hasLegacyNeedle = (value: unknown) =>
  typeof value === "string" && legacyNeedles.some((needle) => value.toLowerCase().includes(needle))
const models = JSON.parse(modelsData) as Record<string, { id?: string; name?: string; models?: Record<string, unknown> }>
for (const providerID of Object.keys(models)) {
  const provider = models[providerID]
  if (hasLegacyNeedle(providerID) || hasLegacyNeedle(provider.id) || hasLegacyNeedle(provider.name)) {
    delete models[providerID]
    continue
  }
  if (!provider.models) continue
  for (const modelID of Object.keys(provider.models)) {
    const model = provider.models[modelID] as { id?: string; name?: string; family?: string }
    if (hasLegacyNeedle(modelID) || hasLegacyNeedle(model.id) || hasLegacyNeedle(model.name) || hasLegacyNeedle(model.family)) {
      delete provider.models[modelID]
    }
  }
}
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${JSON.stringify(models)}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
