/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarGazersRouteImport } from './routes/star-gazers'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsWebsearchRouteImport } from './routes/docs.websearch'
import { Route as DocsUsageRouteImport } from './routes/docs.usage'
import { Route as DocsSubagentsRouteImport } from './routes/docs.subagents'
import { Route as DocsSelfHostingRouteImport } from './routes/docs.self-hosting'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsProvidersRouteImport } from './routes/docs.providers'
import { Route as DocsPluginsRouteImport } from './routes/docs.plugins'
import { Route as DocsMigrationRouteImport } from './routes/docs.migration'
import { Route as DocsMemoryRouteImport } from './routes/docs.memory'
import { Route as DocsMcpRouteImport } from './routes/docs.mcp'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsDreamDistillRouteImport } from './routes/docs.dream-distill'
import { Route as DocsConfigurationRouteImport } from './routes/docs.configuration'
import { Route as DocsComposeRouteImport } from './routes/docs.compose'
import { Route as DocsCommandsRouteImport } from './routes/docs.commands'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsAgentsRouteImport } from './routes/docs.agents'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as ChangelogVersionRouteImport } from './routes/changelog.$version'
import { Route as DocsProvidersXaiRouteImport } from './routes/docs.providers.xai'
import { Route as DocsProvidersOpenrouterRouteImport } from './routes/docs.providers.openrouter'
import { Route as DocsProvidersOpenaiRouteImport } from './routes/docs.providers.openai'
import { Route as DocsProvidersGroqRouteImport } from './routes/docs.providers.groq'
import { Route as DocsProvidersGoogleRouteImport } from './routes/docs.providers.google'
import { Route as DocsProvidersCustomRouteImport } from './routes/docs.providers.custom'
import { Route as DocsProvidersCopilotRouteImport } from './routes/docs.providers.copilot'
import { Route as DocsProvidersAnthropicRouteImport } from './routes/docs.providers.anthropic'

const StarGazersRoute = StarGazersRouteImport.update({
  id: '/star-gazers',
  path: '/star-gazers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWebsearchRoute = DocsWebsearchRouteImport.update({
  id: '/docs/websearch',
  path: '/docs/websearch',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUsageRoute = DocsUsageRouteImport.update({
  id: '/docs/usage',
  path: '/docs/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSubagentsRoute = DocsSubagentsRouteImport.update({
  id: '/docs/subagents',
  path: '/docs/subagents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSelfHostingRoute = DocsSelfHostingRouteImport.update({
  id: '/docs/self-hosting',
  path: '/docs/self-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/docs/quickstart',
  path: '/docs/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProvidersRoute = DocsProvidersRouteImport.update({
  id: '/docs/providers',
  path: '/docs/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPluginsRoute = DocsPluginsRouteImport.update({
  id: '/docs/plugins',
  path: '/docs/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMigrationRoute = DocsMigrationRouteImport.update({
  id: '/docs/migration',
  path: '/docs/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMemoryRoute = DocsMemoryRouteImport.update({
  id: '/docs/memory',
  path: '/docs/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/docs/mcp',
  path: '/docs/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/docs/faq',
  path: '/docs/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDreamDistillRoute = DocsDreamDistillRouteImport.update({
  id: '/docs/dream-distill',
  path: '/docs/dream-distill',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/docs/configuration',
  path: '/docs/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComposeRoute = DocsComposeRouteImport.update({
  id: '/docs/compose',
  path: '/docs/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: '/docs/commands',
  path: '/docs/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAgentsRoute = DocsAgentsRouteImport.update({
  id: '/docs/agents',
  path: '/docs/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogVersionRoute = ChangelogVersionRouteImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => ChangelogRoute,
} as any)
const DocsProvidersXaiRoute = DocsProvidersXaiRouteImport.update({
  id: '/xai',
  path: '/xai',
  getParentRoute: () => DocsProvidersRoute,
} as any)
const DocsProvidersOpenrouterRoute = DocsProvidersOpenrouterRouteImport.update({
  id: '/openrouter',
  path: '/openrouter',
  getParentRoute: () => DocsProvidersRoute,
} as any)
const DocsProvidersOpenaiRoute = DocsProvidersOpenaiRouteImport.update({
  id: '/openai',
  path: '/openai',
  getParentRoute: () => DocsProvidersRoute,
} as any)
const DocsProvidersGroqRoute = DocsProvidersGroqRouteImport.update({
  id: '/groq',
  path: '/groq',
  getParentRoute: () => DocsProvidersRoute,
} as any)
const DocsProvidersGoogleRoute = DocsProvidersGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => DocsProvidersRoute,
} as any)
const DocsProvidersCustomRoute = DocsProvidersCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => DocsProvidersRoute,
} as any)
const DocsProvidersCopilotRoute = DocsProvidersCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => DocsProvidersRoute,
} as any)
const DocsProvidersAnthropicRoute = DocsProvidersAnthropicRouteImport.update({
  id: '/anthropic',
  path: '/anthropic',
  getParentRoute: () => DocsProvidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/community': typeof CommunityRoute
  '/contributors': typeof ContributorsRoute
  '/enterprise': typeof EnterpriseRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/providers': typeof ProvidersRoute
  '/star-gazers': typeof StarGazersRoute
  '/changelog/$version': typeof ChangelogVersionRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/compose': typeof DocsComposeRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/dream-distill': typeof DocsDreamDistillRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/memory': typeof DocsMemoryRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/plugins': typeof DocsPluginsRoute
  '/docs/providers': typeof DocsProvidersRouteWithChildren
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/subagents': typeof DocsSubagentsRoute
  '/docs/usage': typeof DocsUsageRoute
  '/docs/websearch': typeof DocsWebsearchRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/providers/anthropic': typeof DocsProvidersAnthropicRoute
  '/docs/providers/copilot': typeof DocsProvidersCopilotRoute
  '/docs/providers/custom': typeof DocsProvidersCustomRoute
  '/docs/providers/google': typeof DocsProvidersGoogleRoute
  '/docs/providers/groq': typeof DocsProvidersGroqRoute
  '/docs/providers/openai': typeof DocsProvidersOpenaiRoute
  '/docs/providers/openrouter': typeof DocsProvidersOpenrouterRoute
  '/docs/providers/xai': typeof DocsProvidersXaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/community': typeof CommunityRoute
  '/contributors': typeof ContributorsRoute
  '/enterprise': typeof EnterpriseRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/providers': typeof ProvidersRoute
  '/star-gazers': typeof StarGazersRoute
  '/changelog/$version': typeof ChangelogVersionRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/compose': typeof DocsComposeRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/dream-distill': typeof DocsDreamDistillRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/memory': typeof DocsMemoryRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/plugins': typeof DocsPluginsRoute
  '/docs/providers': typeof DocsProvidersRouteWithChildren
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/subagents': typeof DocsSubagentsRoute
  '/docs/usage': typeof DocsUsageRoute
  '/docs/websearch': typeof DocsWebsearchRoute
  '/docs': typeof DocsIndexRoute
  '/docs/providers/anthropic': typeof DocsProvidersAnthropicRoute
  '/docs/providers/copilot': typeof DocsProvidersCopilotRoute
  '/docs/providers/custom': typeof DocsProvidersCustomRoute
  '/docs/providers/google': typeof DocsProvidersGoogleRoute
  '/docs/providers/groq': typeof DocsProvidersGroqRoute
  '/docs/providers/openai': typeof DocsProvidersOpenaiRoute
  '/docs/providers/openrouter': typeof DocsProvidersOpenrouterRoute
  '/docs/providers/xai': typeof DocsProvidersXaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/community': typeof CommunityRoute
  '/contributors': typeof ContributorsRoute
  '/enterprise': typeof EnterpriseRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/providers': typeof ProvidersRoute
  '/star-gazers': typeof StarGazersRoute
  '/changelog/$version': typeof ChangelogVersionRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/compose': typeof DocsComposeRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/dream-distill': typeof DocsDreamDistillRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/memory': typeof DocsMemoryRoute
  '/docs/migration': typeof DocsMigrationRoute
  '/docs/plugins': typeof DocsPluginsRoute
  '/docs/providers': typeof DocsProvidersRouteWithChildren
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/subagents': typeof DocsSubagentsRoute
  '/docs/usage': typeof DocsUsageRoute
  '/docs/websearch': typeof DocsWebsearchRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/providers/anthropic': typeof DocsProvidersAnthropicRoute
  '/docs/providers/copilot': typeof DocsProvidersCopilotRoute
  '/docs/providers/custom': typeof DocsProvidersCustomRoute
  '/docs/providers/google': typeof DocsProvidersGoogleRoute
  '/docs/providers/groq': typeof DocsProvidersGroqRoute
  '/docs/providers/openai': typeof DocsProvidersOpenaiRoute
  '/docs/providers/openrouter': typeof DocsProvidersOpenrouterRoute
  '/docs/providers/xai': typeof DocsProvidersXaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/changelog'
    | '/community'
    | '/contributors'
    | '/enterprise'
    | '/features'
    | '/pricing'
    | '/providers'
    | '/star-gazers'
    | '/changelog/$version'
    | '/docs/$'
    | '/docs/agents'
    | '/docs/api'
    | '/docs/commands'
    | '/docs/compose'
    | '/docs/configuration'
    | '/docs/dream-distill'
    | '/docs/faq'
    | '/docs/mcp'
    | '/docs/memory'
    | '/docs/migration'
    | '/docs/plugins'
    | '/docs/providers'
    | '/docs/quickstart'
    | '/docs/self-hosting'
    | '/docs/subagents'
    | '/docs/usage'
    | '/docs/websearch'
    | '/docs/'
    | '/docs/providers/anthropic'
    | '/docs/providers/copilot'
    | '/docs/providers/custom'
    | '/docs/providers/google'
    | '/docs/providers/groq'
    | '/docs/providers/openai'
    | '/docs/providers/openrouter'
    | '/docs/providers/xai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/changelog'
    | '/community'
    | '/contributors'
    | '/enterprise'
    | '/features'
    | '/pricing'
    | '/providers'
    | '/star-gazers'
    | '/changelog/$version'
    | '/docs/$'
    | '/docs/agents'
    | '/docs/api'
    | '/docs/commands'
    | '/docs/compose'
    | '/docs/configuration'
    | '/docs/dream-distill'
    | '/docs/faq'
    | '/docs/mcp'
    | '/docs/memory'
    | '/docs/migration'
    | '/docs/plugins'
    | '/docs/providers'
    | '/docs/quickstart'
    | '/docs/self-hosting'
    | '/docs/subagents'
    | '/docs/usage'
    | '/docs/websearch'
    | '/docs'
    | '/docs/providers/anthropic'
    | '/docs/providers/copilot'
    | '/docs/providers/custom'
    | '/docs/providers/google'
    | '/docs/providers/groq'
    | '/docs/providers/openai'
    | '/docs/providers/openrouter'
    | '/docs/providers/xai'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/changelog'
    | '/community'
    | '/contributors'
    | '/enterprise'
    | '/features'
    | '/pricing'
    | '/providers'
    | '/star-gazers'
    | '/changelog/$version'
    | '/docs/$'
    | '/docs/agents'
    | '/docs/api'
    | '/docs/commands'
    | '/docs/compose'
    | '/docs/configuration'
    | '/docs/dream-distill'
    | '/docs/faq'
    | '/docs/mcp'
    | '/docs/memory'
    | '/docs/migration'
    | '/docs/plugins'
    | '/docs/providers'
    | '/docs/quickstart'
    | '/docs/self-hosting'
    | '/docs/subagents'
    | '/docs/usage'
    | '/docs/websearch'
    | '/docs/'
    | '/docs/providers/anthropic'
    | '/docs/providers/copilot'
    | '/docs/providers/custom'
    | '/docs/providers/google'
    | '/docs/providers/groq'
    | '/docs/providers/openai'
    | '/docs/providers/openrouter'
    | '/docs/providers/xai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  ChangelogRoute: typeof ChangelogRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContributorsRoute: typeof ContributorsRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  ProvidersRoute: typeof ProvidersRoute
  StarGazersRoute: typeof StarGazersRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsAgentsRoute: typeof DocsAgentsRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsCommandsRoute: typeof DocsCommandsRoute
  DocsComposeRoute: typeof DocsComposeRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsDreamDistillRoute: typeof DocsDreamDistillRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsMcpRoute: typeof DocsMcpRoute
  DocsMemoryRoute: typeof DocsMemoryRoute
  DocsMigrationRoute: typeof DocsMigrationRoute
  DocsPluginsRoute: typeof DocsPluginsRoute
  DocsProvidersRoute: typeof DocsProvidersRouteWithChildren
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsSelfHostingRoute: typeof DocsSelfHostingRoute
  DocsSubagentsRoute: typeof DocsSubagentsRoute
  DocsUsageRoute: typeof DocsUsageRoute
  DocsWebsearchRoute: typeof DocsWebsearchRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/star-gazers': {
      id: '/star-gazers'
      path: '/star-gazers'
      fullPath: '/star-gazers'
      preLoaderRoute: typeof StarGazersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/websearch': {
      id: '/docs/websearch'
      path: '/docs/websearch'
      fullPath: '/docs/websearch'
      preLoaderRoute: typeof DocsWebsearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/usage': {
      id: '/docs/usage'
      path: '/docs/usage'
      fullPath: '/docs/usage'
      preLoaderRoute: typeof DocsUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/subagents': {
      id: '/docs/subagents'
      path: '/docs/subagents'
      fullPath: '/docs/subagents'
      preLoaderRoute: typeof DocsSubagentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/self-hosting': {
      id: '/docs/self-hosting'
      path: '/docs/self-hosting'
      fullPath: '/docs/self-hosting'
      preLoaderRoute: typeof DocsSelfHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/docs/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/providers': {
      id: '/docs/providers'
      path: '/docs/providers'
      fullPath: '/docs/providers'
      preLoaderRoute: typeof DocsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/plugins': {
      id: '/docs/plugins'
      path: '/docs/plugins'
      fullPath: '/docs/plugins'
      preLoaderRoute: typeof DocsPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/migration': {
      id: '/docs/migration'
      path: '/docs/migration'
      fullPath: '/docs/migration'
      preLoaderRoute: typeof DocsMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/memory': {
      id: '/docs/memory'
      path: '/docs/memory'
      fullPath: '/docs/memory'
      preLoaderRoute: typeof DocsMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/docs/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/docs/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/dream-distill': {
      id: '/docs/dream-distill'
      path: '/docs/dream-distill'
      fullPath: '/docs/dream-distill'
      preLoaderRoute: typeof DocsDreamDistillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/docs/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/compose': {
      id: '/docs/compose'
      path: '/docs/compose'
      fullPath: '/docs/compose'
      preLoaderRoute: typeof DocsComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/commands': {
      id: '/docs/commands'
      path: '/docs/commands'
      fullPath: '/docs/commands'
      preLoaderRoute: typeof DocsCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/agents': {
      id: '/docs/agents'
      path: '/docs/agents'
      fullPath: '/docs/agents'
      preLoaderRoute: typeof DocsAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$version': {
      id: '/changelog/$version'
      path: '/$version'
      fullPath: '/changelog/$version'
      preLoaderRoute: typeof ChangelogVersionRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/docs/providers/xai': {
      id: '/docs/providers/xai'
      path: '/xai'
      fullPath: '/docs/providers/xai'
      preLoaderRoute: typeof DocsProvidersXaiRouteImport
      parentRoute: typeof DocsProvidersRoute
    }
    '/docs/providers/openrouter': {
      id: '/docs/providers/openrouter'
      path: '/openrouter'
      fullPath: '/docs/providers/openrouter'
      preLoaderRoute: typeof DocsProvidersOpenrouterRouteImport
      parentRoute: typeof DocsProvidersRoute
    }
    '/docs/providers/openai': {
      id: '/docs/providers/openai'
      path: '/openai'
      fullPath: '/docs/providers/openai'
      preLoaderRoute: typeof DocsProvidersOpenaiRouteImport
      parentRoute: typeof DocsProvidersRoute
    }
    '/docs/providers/groq': {
      id: '/docs/providers/groq'
      path: '/groq'
      fullPath: '/docs/providers/groq'
      preLoaderRoute: typeof DocsProvidersGroqRouteImport
      parentRoute: typeof DocsProvidersRoute
    }
    '/docs/providers/google': {
      id: '/docs/providers/google'
      path: '/google'
      fullPath: '/docs/providers/google'
      preLoaderRoute: typeof DocsProvidersGoogleRouteImport
      parentRoute: typeof DocsProvidersRoute
    }
    '/docs/providers/custom': {
      id: '/docs/providers/custom'
      path: '/custom'
      fullPath: '/docs/providers/custom'
      preLoaderRoute: typeof DocsProvidersCustomRouteImport
      parentRoute: typeof DocsProvidersRoute
    }
    '/docs/providers/copilot': {
      id: '/docs/providers/copilot'
      path: '/copilot'
      fullPath: '/docs/providers/copilot'
      preLoaderRoute: typeof DocsProvidersCopilotRouteImport
      parentRoute: typeof DocsProvidersRoute
    }
    '/docs/providers/anthropic': {
      id: '/docs/providers/anthropic'
      path: '/anthropic'
      fullPath: '/docs/providers/anthropic'
      preLoaderRoute: typeof DocsProvidersAnthropicRouteImport
      parentRoute: typeof DocsProvidersRoute
    }
  }
}

interface ChangelogRouteChildren {
  ChangelogVersionRoute: typeof ChangelogVersionRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogVersionRoute: ChangelogVersionRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

interface DocsProvidersRouteChildren {
  DocsProvidersAnthropicRoute: typeof DocsProvidersAnthropicRoute
  DocsProvidersCopilotRoute: typeof DocsProvidersCopilotRoute
  DocsProvidersCustomRoute: typeof DocsProvidersCustomRoute
  DocsProvidersGoogleRoute: typeof DocsProvidersGoogleRoute
  DocsProvidersGroqRoute: typeof DocsProvidersGroqRoute
  DocsProvidersOpenaiRoute: typeof DocsProvidersOpenaiRoute
  DocsProvidersOpenrouterRoute: typeof DocsProvidersOpenrouterRoute
  DocsProvidersXaiRoute: typeof DocsProvidersXaiRoute
}

const DocsProvidersRouteChildren: DocsProvidersRouteChildren = {
  DocsProvidersAnthropicRoute: DocsProvidersAnthropicRoute,
  DocsProvidersCopilotRoute: DocsProvidersCopilotRoute,
  DocsProvidersCustomRoute: DocsProvidersCustomRoute,
  DocsProvidersGoogleRoute: DocsProvidersGoogleRoute,
  DocsProvidersGroqRoute: DocsProvidersGroqRoute,
  DocsProvidersOpenaiRoute: DocsProvidersOpenaiRoute,
  DocsProvidersOpenrouterRoute: DocsProvidersOpenrouterRoute,
  DocsProvidersXaiRoute: DocsProvidersXaiRoute,
}

const DocsProvidersRouteWithChildren = DocsProvidersRoute._addFileChildren(
  DocsProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  ChangelogRoute: ChangelogRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContributorsRoute: ContributorsRoute,
  EnterpriseRoute: EnterpriseRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  ProvidersRoute: ProvidersRoute,
  StarGazersRoute: StarGazersRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsAgentsRoute: DocsAgentsRoute,
  DocsApiRoute: DocsApiRoute,
  DocsCommandsRoute: DocsCommandsRoute,
  DocsComposeRoute: DocsComposeRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsDreamDistillRoute: DocsDreamDistillRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsMcpRoute: DocsMcpRoute,
  DocsMemoryRoute: DocsMemoryRoute,
  DocsMigrationRoute: DocsMigrationRoute,
  DocsPluginsRoute: DocsPluginsRoute,
  DocsProvidersRoute: DocsProvidersRouteWithChildren,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsSelfHostingRoute: DocsSelfHostingRoute,
  DocsSubagentsRoute: DocsSubagentsRoute,
  DocsUsageRoute: DocsUsageRoute,
  DocsWebsearchRoute: DocsWebsearchRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
